### ISSUE TITLE
Still issue of styling master document from stylesheet using html imports is persisting

### ISSUE THREAD

**Issue by gauravonly** [TakayoshiKochi/deprecate-style-in-html-imports#2]
I have followed as it was instructed but still i am getting the same error. Any know how about the issue will help a lot???

**Comment by TakayoshiKochi** [comment]
Do you use HTML Imports with Polymer or do you directly use HTML Imports?

**Comment by infiman** [comment]
@TakayoshiKochi as I've understood from examples, none of these fixes are removing initial loading/applying of styles when the import is resolved. All these fixes are just for the sake of styles duplication in masters head either by loading (```<link>```) or "styling" (```<style>```), right? Correct me if I'm wrong. 

Also, I'm curious how removing "style-in-html-imports" feature in Chrome will affect all unfixed imports? Will it not import/apply styles at all?

I've tried to apply these fixes to some external styles. And I'm getting multiple imports of same CSS resource (from index.html and import.html), what is not really good.

1. Structure:
![image](https://user-images.githubusercontent.com/3742829/34179452-9b84b67e-e513-11e7-89f9-c2812baf796b.png)
1. Network:
![image](https://user-images.githubusercontent.com/3742829/34179461-a83cf19c-e513-11e7-9d30-5c31da43c18b.png)

**Comment by TakayoshiKochi** [comment]
Sorry for the delay in responding.
So the problem of still getting the warning is, e.g.

main.html
```
<link rel="import" href="import.html">
...
```

import.html
```
<style>
div { color: green; }
...
</style>
```

and if any workarounds, such as using JavaScript code to move the <style> header in import.html to main.html, would still put a warning message on your console, when your import.html is first parsed.
(BTW This still happens with the latest Polymer with the updated `<custom-style>` element.)

Once Chrome removes style application from imports (scheduled in M65), any stylesheet contents (i.e. CSS in `<style>` in any HTML import file) will not apply to the main document.

So the permanent fix would be
1. remove `<style>` element (or `<link rel=stylesheet>)` in HTML imports source file
2. put the removed `<style>` contents in main document HTML
then you should be able to avoid multiple loadings of the same stylesheet.

I'm not sure I fully understand your problem, let me know if further clarification needed.
Thanks!

**Comment by infiman** [comment]
@TakayoshiKochi thanks for your reply. It was helpful.

**Comment by TakayoshiKochi** [comment]
@gauravkk22 if your concern is resolved, please close this, or not, let me know.
We are going to remove stylesheet application from HTML Imports entirely in Chrome soon (planned M65, which is released in Mar. 2018).
