### ISSUE TITLE
Possible to preview effect of change earlier than June 2018?

### ISSUE THREAD

**Issue by donmccurdy** [TakayoshiKochi/deprecate-style-in-html-imports#7]
Is there a flag or some other way for developers to preview the effect of this change, without waiting for it to roll out to everyone?

I'm using Polymer and have updated most of my dependencies but still see the error, and am not sure if that's just a stray `div` selector leaking to master document (which I wouldn't really care about) or whether some dependency is actually depending on this behavior.

Thanks!

**Comment by TakayoshiKochi** [comment]
Could you try passing `--disable-blink-features=HTMLImportsStyleApplication` option to chrome binary?

**Comment by donmccurdy** [comment]
In Chrome v64 and Chrome Canary I see: 

```
You are using an unsupported command-line flag: --disable-blink-features=HTMLImportsStyleApplication. Stability and security will suffer.
```

**Comment by TakayoshiKochi** [comment]
You can ignore what the infobar (with yellow background on top of web contents) says.
What the inforbar says is true, that it is not "supported" if you run Chrome with that flag, but it is for experimenting with some setting off, so please go ahead testing your site.

**Comment by donmccurdy** [comment]
Ok thanks! I still see the deprecation notice in the console, and no visible change to my site.. I guess that is good news / just some minor style leaked from my CSS?

**Comment by TakayoshiKochi** [comment]
The problem (for us, the implementors) is that even you move your `<style>` from your import file to the main document (e.g. via (`document.body.appendChild(styleElement)`)), we still put the deprecation message upon **parsing** the `<style>` element in the import file, before running the script to move the element out of the import.

So, if you provide the option and you don't do any workaround, you'll see your style from the import won't get applied to the document and some styling / layout should break, while if you have some workaround there, you will see the expected rendering of the page, even though the deprecation warning is still there in the console.

**Comment by donmccurdy** [comment]
Makes sense, thanks :)
