### ISSUE TITLE
Website link is dead

### ISSUE THREAD

**Issue by shahzeb1** [TakayoshiKochi/deprecate-style-in-html-imports#9]
For me the following link is an empty white page: https://takayoshikochi.github.io/deprecate-style-in-html-imports/

**Comment by TakayoshiKochi** [comment]
Thanks for the report.
The site in GitHub pages is used just for serving the examples, and the main document should be this repository's README.md.  I added a link on the page to README.md.

BTW, where did you find the link?  If there is the direct link to the top page somewhere, I'll fix it also.

**Comment by shahzeb1** [comment]
Sure so I found [the link here](https://github.com/TakayoshiKochi/deprecate-style-in-html-imports/blob/6c0bf1a2d6165c5e8338fd9eef1e9984d312b548/README.md#L31)

**Comment by TakayoshiKochi** [comment]
Thanks, the page (GitHub showing the README.md) now does not contain a direct link to the top page, only subpages, so I hope it is not that problematic for now.

**Comment by shahzeb1** [comment]
Huh, interesting.

I can still find it on [search](https://github.com/TakayoshiKochi/deprecate-style-in-html-imports/search?q=deprecate-style-in-html-imports&unscoped_q=deprecate-style-in-html-imports). Does github show old commits on the search page? 

Most likely this issue has been resolved 😄

**Comment by TakayoshiKochi** [comment]
No, I meant [the direct link to the top page](https://takayoshikochi.github.io/deprecate-style-in-html-imports/) (like this) is not in README.md any more.
A link to its subtrees which has actual page is not an issue.
